// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClApTIj3WDNzeJ5x1RbALST9M7_jMj8DA',
    appId: '1:950499379321:web:ccf9eedd0d498971f3aca8',
    messagingSenderId: '950499379321',
    projectId: 'areonix-91035',
    authDomain: 'areonix-91035.firebaseapp.com',
    storageBucket: 'areonix-91035.appspot.com',
    measurementId: 'G-DRPK0NR7DY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMR6U3HAE8KYlbwoWJXIfRaC4Ic_3o68g',
    appId: '1:950499379321:android:3d8cef34bdc7ac27f3aca8',
    messagingSenderId: '950499379321',
    projectId: 'areonix-91035',
    storageBucket: 'areonix-91035.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxVuyqyVpA-xdPfvMownysIyW6OH-Tc1E',
    appId: '1:950499379321:ios:938c0cf99950937df3aca8',
    messagingSenderId: '950499379321',
    projectId: 'areonix-91035',
    storageBucket: 'areonix-91035.appspot.com',
    iosBundleId: 'com.example.areonix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxVuyqyVpA-xdPfvMownysIyW6OH-Tc1E',
    appId: '1:950499379321:ios:938c0cf99950937df3aca8',
    messagingSenderId: '950499379321',
    projectId: 'areonix-91035',
    storageBucket: 'areonix-91035.appspot.com',
    iosBundleId: 'com.example.areonix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClApTIj3WDNzeJ5x1RbALST9M7_jMj8DA',
    appId: '1:950499379321:web:5333d2fb9ba7dfe5f3aca8',
    messagingSenderId: '950499379321',
    projectId: 'areonix-91035',
    authDomain: 'areonix-91035.firebaseapp.com',
    storageBucket: 'areonix-91035.appspot.com',
    measurementId: 'G-K1Q3R65CCY',
  );
}
